# Generated by Django 2.0.3 on 2018-03-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('ping_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('host_name', models.TextField(verbose_name='Server hostname')),
                ('alias', models.TextField(blank=True, verbose_name='Display name')),
                ('groups', models.TextField(blank=True, verbose_name='Groups')),
            ],
        ),
    ]
