# Generated by Django 2.0.3 on 2018-03-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Host',
            new_name='Hosts',
        ),
    ]
