# Generated by Django 2.0.3 on 2018-03-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0002_auto_20180322_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='alias',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='groups',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='host_name',
            field=models.TextField(),
        ),
    ]
