# Generated by Django 2.0.3 on 2018-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_auto_20180323_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='alias',
            field=models.TextField(blank=True, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='groups',
            field=models.TextField(blank=True, verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='host_name',
            field=models.TextField(verbose_name='Server hostname'),
        ),
    ]
